/**
 * Auto-generated by dotnet-to-ts
 * Generated on: 2026-01-21T09:37:09.732Z
 * DO NOT EDIT MANUALLY
 */

export interface DepartmentDto {
  Id: number;
  Name: string;
  Location: string;
}

/**
 * Auto-generated by dotnet-to-ts
 * Generated on: 2026-01-21T09:37:09.734Z
 * DO NOT EDIT MANUALLY
 */

export interface EmployeeDto {
  Id: number;
  Name: string;
  Email: string;
  IsActive: boolean;
  DepartmentId: number;
}

/**
 * Auto-generated by dotnet-to-ts
 * Generated on: 2026-01-21T09:37:09.734Z
 * DO NOT EDIT MANUALLY
 */

export interface EmployeeViewModel {
  Id: number;
  Name: string;
  Entity: EntityDto;
  Department: DepartmentDto;
  Roles: string[];
  LastLogin: string;
  IsActive: boolean;
}

/**
 * Auto-generated by dotnet-to-ts
 * Generated on: 2026-01-21T09:37:09.734Z
 * DO NOT EDIT MANUALLY
 */

export interface EntityDto {
  Id: number;
  Name: string;
  Code: string;
}